# git 示例
# 唯一ID，必须为英文
[title]
# 类型
type = "git"
#商店外显名字（可选，不写则显示唯一ID）
shop_name = "我要头衔"
# 插件类型（可选，默认为 normal ，框架本体拓展为 expand ）
plugin_type = "normal"
# 包的名称
package_name = "kovi-plugin-title"
# 插件描述
description = "kovi 的头衔插件。"
# git 地址
git_url = "https://github.com/kovi-plugins/kovi-plugin-title.git"
# 插件仓库地址
repository = "https://github.com/kovi-plugins/kovi-plugin-title"
# 文档地址（可选）
documentation = "https://github.com/kovi-plugins/kovi-plugin-title"
# 作者
author_name = "三瓶可乐不过岗"
# 作者链接（可选）
author_url = "https://github.com/thricecola"
# 作者头像链接（可选）
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"


# crates.io 示例
# 唯一ID，必须为英文
[like]
# 类型
type = "crates.io"
#商店外显名字（可选，不写则显示唯一ID）
shop_name = "like"
# 插件类型（可选，默认为 normal ，框架本体拓展为 expand ）
plugin_type = "normal"
# 包的名称
package_name = "kovi-plugin-like"
# 插件描述
description = "kovi 的点赞插件，可在config.json里配置。"
# 插件仓库地址（可选）
repository = "https://github.com/kovi-plugins/kovi-plugin-like"
# 文档地址（可选）
documentation = "https://github.com/kovi-plugins/kovi-plugin-like"
# 作者（可选，不写则获取crates.io的数据）
author_name = "三瓶可乐不过岗"
# 作者链接（可选，不写则获取crates.io的数据）
author_url = "https://github.com/thricecola"
# 作者链接（可选，不写则获取crates.io的数据）
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"


[expand-lagrange]
type = "crates.io"
plugin_type = "expand"
package_name = "kovi-plugin-expand-lagrange"
description = "kovi 的 lagrange Api 拓展。"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[expand-napcat]
type = "crates.io"
plugin_type = "expand"
package_name = "kovi-plugin-expand-napcat"
description = "kovi 的 napcat Api 拓展。"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[cmd]
type = "crates.io"
package_name = "kovi-plugin-cmd"
description = "Kovi 的管理插件，通过消息命令配置 Kovi。"
repository = "https://github.com/kovi-plugins/cmd"
documentation = "https://crates.io/crates/kovi-plugin-cmd"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[shindan-maker]
type = "crates.io"
shop_name = "shindan-maker"
package_name = "kovi-plugin-shindan-maker"
description = "Kovi 的 ShindanMaker 占卜插件。"
repository = "https://github.com/araea/kovi-plugin-shindan-maker"
documentation = "https://github.com/araea/kovi-plugin-shindan-maker"
author_name = "NAWYJX"
author_url = "https://github.com/araea"
avatar_url = "https://avatars.githubusercontent.com/u/120614554?v=4"

[getpic]
type = "git"
shop_name = "来点图片"
package_name = "kovi-plugin-getpic"
description = "可以获取你想要的图片的插件。"
git_url = "https://github.com/super1207/kovi-plugin-getpic.git"
repository = "https://github.com/super1207/kovi-plugin-getpic"
documentation = "https://github.com/super1207/kovi-plugin-getpic"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[runpy]
type = "git"
shop_name = "运行py"
package_name = "kovi-plugin-runpy"
description = "用于为其它插件提供运行python脚本的能力(试验中)"
git_url = "https://github.com/super1207/kovi-plugin-runpy.git"
repository = "https://github.com/super1207/kovi-plugin-runpy"
documentation = "https://github.com/super1207/kovi-plugin-runpy"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[guess-music]
type = "git"
shop_name = "猜歌"
package_name = "kovi-plugin-guess-music"
description = "用于根据一些乱七八糟的信息来猜测歌手和歌名"
git_url = "https://github.com/super1207/kovi-plugin-guess-music.git"
repository = "https://github.com/super1207/kovi-plugin-guess-music"
documentation = "https://github.com/super1207/kovi-plugin-guess-music"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[check-all-long]
type = "git"
shop_name = "检测龙图与奶龙"
package_name = "kovi-plugin-check-alllong"
description = "检测龙图或者奶龙并撤回"
git_url = "https://github.com/kovi-plugins/check-all-long.git"
repository = "https://github.com/kovi-plugins/check-all-long"
documentation = "https://github.com/kovi-plugins/check-all-long"
author_name = "三瓶可乐不过岗-不官方"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[local-chat-model]
type = "git"
shop_name = "机器人芸汐"
package_name = "kovi-plugin-local-chat-model"
description = "基于ollama的本地大模型插件"
git_url = "git@github.com:yunshenOwO/local-chat-model.git"
repository = "https://github.com/yunshenOwO/local-chat-model"
author_name = "云深不知处"
author_url = "https://github.com/yunshenOwO"
avatar_url = "https://avatars.githubusercontent.com/u/155443399?v=4"

[momo-bot]
type = "crates.io"
shop_name = "momo-bot"
package_name = "kovi-plugin-live-agent"
description = "群消息持久化和csv导出，对消息记录有感知的AI对话，哔哩哔哩直播通知"
repository = "https://github.com/realzhujunhao/momo-bot"
documentation = "https://docs.rs/kovi-plugin-live-agent/latest/kovi_plugin_live_agent"
author_name = "梦梦永远の神"
author_url = "https://github.com/realzhujunhao"
avatar_url = "https://avatars.githubusercontent.com/u/63294481?v=4"

[aiqa]
type = "git"
shop_name = "AI问答"
package_name = "kovi-plugin-aiqa"
description = "一次性的ai问答，并且输出图片，兼容openai的模型皆可用"
git_url = "https://github.com/kovi-plugins/aiqa.git"
repository = "https://github.com/kovi-plugins/aiqa"
documentation = "https://github.com/kovi-plugins/aiqa"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[kovi-plugin-siliconflow]
type = "crates.io"
shop_name = "硅基流动-Ai"
package_name = "kovi-plugin-siliconflow"
description = "一款基于 kovi 的对接硅基流动的机器人问答插件"
repository = "https://github.com/Admsec/kovi-plugin-siliconflow"
author_name = "Admsec"
author_url = "https://github.com/Admsec/"
avatar_url = "https://avatars.githubusercontent.com/u/86643414?v=4"


[event-engine]
type = "git"
shop_name = "事件驱动器"
plugin_type = "expand"
package_name = "kovi-plugin-event-engine"
description = "kovi 的额外事件驱动器。"
git_url = "https://github.com/kovi-plugins/event-engine.git"
repository = "https://github.com/kovi-plugins/event-engine"
documentation = "https://github.com/kovi-plugins/event-engine"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/thricecola"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"


[copycat]
type = "crates.io"
plugin_type = "normal"
package_name = "kovi-plugin-copycat"
description = "基于 kovi 的自动复读插件"
git_url = "https://github.com/Hamster5295/copycat.git"
repository = "https://github.com/Hamster5295/copycat"
documentation = "https://github.com/Hamster5295/copycat/blob/main/README.md"
author_name = "Hamster5295"
author_url = "https://github.com/Hamster5295"
avatar_url = "https://avatars.githubusercontent.com/u/37259613?v=4"


[pet-cat]
type = "crates.io"
plugin_type = "normal"
package_name = "kovi-plugin-pet-cat"
description = "基于 kovi 的自动撸猫插件"
git_url = "https://github.com/Hamster5295/pet-cat.git"
repository = "https://github.com/Hamster5295/pet-cat"
documentation = "https://github.com/Hamster5295/pet-cat/blob/main/README.md"
author_name = "Hamster5295"
author_url = "https://github.com/Hamster5295"
avatar_url = "https://avatars.githubusercontent.com/u/37259613?v=4"
