# git 示例
# 唯一ID，必须为英文
[title]
# 类型
type = "git"
#商店外显名字（可选，不写则显示唯一ID）
shop_name = "我要头衔"
# 插件类型（可选，默认为normal）
plugin_type = "normal"
# 包的名称
package_name = "kovi-plugin-title"
# 插件描述
description = "kovi 的头衔插件。"
# git 地址
git_url = "https://github.com/Threkork/kovi-plugin-title.git"
# 插件仓库地址
repository = "https://github.com/Threkork/kovi-plugin-title"
# 文档地址（可选）
documentation = "https://github.com/Threkork/kovi-plugin-title"
# 作者 
author_name = "三瓶可乐不过岗"
# 作者链接（可选） 
author_url = "https://github.com/Threkork"
# 作者头像链接（可选）
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"


# crates.io 示例
# 唯一ID，必须为英文
[like]
# 类型
type = "crates.io"
#商店外显名字（可选，不写则显示唯一ID）
shop_name = "like"
# 插件类型（可选，默认为normal）
plugin_type = "normal"
# 包的名称
package_name = "kovi-plugin-like"
# 插件描述
description = "kovi 的点赞插件，可在config.json里配置。"
# 插件仓库地址（可选）
repository = "https://github.com/Threkork/kovi-plugin"
# 文档地址（可选）
documentation = "https://github.com/Threkork/kovi-plugin"
# 作者（可选，不写则获取crates.io的数据）
author_name = "三瓶可乐不过岗"
# 作者链接（可选，不写则获取crates.io的数据） 
author_url = "https://github.com/Threkork"
# 作者链接（可选，不写则获取crates.io的数据） 
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"


[expand-lagrange]
type = "crates.io"
plugin_type = "expand"
package_name = "kovi-plugin-expand-lagrange"
description = "kovi 的 lagrange Api 拓展。"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/Threkork"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[expand-napcat]
type = "crates.io"
plugin_type = "expand"
package_name = "kovi-plugin-expand-napcat"
description = "kovi 的 napcat Api 拓展。"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/Threkork"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[shindan-maker]
type = "crates.io"
shop_name = "shindan-maker"
package_name = "kovi-plugin-shindan-maker"
description = "Kovi 的 ShindanMaker 占卜插件。"
repository = "https://github.com/araea/kovi-plugin-shindan-maker"
documentation = "https://github.com/araea/kovi-plugin-shindan-maker"
author_name = "NAWYJX"
author_url = "https://github.com/araea"
avatar_url = "https://avatars.githubusercontent.com/u/120614554?v=4"

[getpic]
type = "git"
shop_name = "来点图片"
package_name = "kovi-plugin-getpic"
description = "可以获取你想要的图片的插件。"
git_url = "https://github.com/super1207/kovi-plugin-getpic.git"
repository = "https://github.com/super1207/kovi-plugin-getpic"
documentation = "https://github.com/super1207/kovi-plugin-getpic"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[runpy]
type = "git"
shop_name = "运行py"
package_name = "kovi-plugin-runpy"
description = "用于为其它插件提供运行python脚本的能力(试验中)"
git_url = "https://github.com/super1207/kovi-plugin-runpy.git"
repository = "https://github.com/super1207/kovi-plugin-runpy"
documentation = "https://github.com/super1207/kovi-plugin-runpy"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[guess-music]
type = "git"
shop_name = "猜歌"
package_name = "kovi-plugin-guess-music"
description = "用于根据一些乱七八糟的信息来猜测歌手和歌名"
git_url = "https://github.com/super1207/kovi-plugin-guess-music.git"
repository = "https://github.com/super1207/kovi-plugin-guess-music"
documentation = "https://github.com/super1207/kovi-plugin-guess-music"
author_name = "super1207"
author_url = "https://github.com/super1207"
avatar_url = "https://avatars.githubusercontent.com/u/30586004?v=4"

[check-alllong]
type = "git"
shop_name = "检测龙图与奶龙"
package_name = "kovi-plugin-check-alllong"
description = "检测龙图或者奶龙并撤回"
git_url = "https://github.com/Threkork/kovi-plugin-check-alllong.git"
repository = "https://github.com/Threkork/kovi-plugin-check-alllong"
documentation = "https://github.com/Threkork/kovi-plugin-check-alllong"
author_name = "三瓶可乐不过岗"
author_url = "https://github.com/Threkork"
avatar_url = "https://avatars.githubusercontent.com/u/92619280?v=4"

[local-chat-model]
type = "git"
shop_name = "机器人芸汐"
package_name = "kovi-plugin-local-chat-model"
description = "基于ollama的本地大模型插件"
git_url = "git@github.com:yunshenOwO/local-chat-model.git"
repository = "https://github.com/yunshenOwO/local-chat-model"
author_name = "云深不知处"
author_url = "https://github.com/yunshenOwO"
avatar_url = "https://avatars.githubusercontent.com/u/155443399?v=4"
